export const ARTISTS = [
  "BTS", "IU", "TWICE", "aespa", "NewJeans", "ITZY", "MAMAMOO",
  "Stray Kids", "GOT7", "SHINee", "BIGBANG", "EXO", "SEVENTEEN",
  "ATEEZ", "TXT", "ENHYPEN", "Le Sserafim", "NMIXX", "DAY6",
  "MONSTA X", "Block B", "CN Blue", "Super Junior",
  "BUZZ", "박효신", "나얼", "강민경", "다비치", "버스커버스커",
  "10cm", "성시경", "빅마마", "인순이", "이승환", "이수현",
  "AKMU", "윤하", "케이윌", "소향", "김필", "이문세",
  "태연", "효린", "빅뱅", "소녀시대", "에이핑크",
  "SUPER JUNIOR", "BLACKPINK", "RED VELVET", "TOMORROW X TOGETHER",
  "Taylor Swift", "Ed Sheeran", "Drake", "Beyonce", "Adele",
  "Eminem", "Rihanna", "Bruno Mars", "Coldplay", "Radiohead",
  "Nirvana", "Oasis", "Gorillaz", "Muse", "Arctic Monkeys",
  "Linkin Park", "Green Day", "Blink-182", "Paramore", "Lorde",
  "Lana Del Rey", "Billie Eilish", "Olivia Rodrigo", "Dua Lipa",
  "Harry Styles", "Ariana Grande", "Post Malone", "The Weeknd",
  "Kendrick Lamar", "J Cole", "Travis Scott", "Kanye West",
  "Twenty One Pilots", "Imagine Dragons", "Maroon 5", "OneRepublic",
  "The Killers", "Bastille", "Tame Impala", "Florence",
  "Michael Jackson", "Prince", "Elton John", "Queen",
  "David Bowie", "Bob Dylan", "The Rolling Stones", "The Beatles",
]
